class englishText {
    translateButton = "SRB";
    textId1 = "Home";
    textId2 = "About";
    textId3 = "Services";
    textId4 = "Portfolio";
    textId5 = "Contact";
    //textId6 = "Message";
    textId7a = "Hello!";
    textId7 = "We are GisIt.<br>We think spatially<br>& build great apps.";
    textId8a = "Scroll Down";
    textId9 = "GisIt is an agency specialized in providing IT services in the field of Geographic Information Systems (GIS), as well as related areas such as photogrammetry and LiDAR technology.";
    textId10 = "Our mission is to enhance our clients' business processes through innovative technological solutions that assist in improving their operations and making informed, timely business decisions.";
    textId11a = "Expertise and Experience";
    textId11 = "Our team is made up of people with a lot of experience in GIS, photogrammetry, and LiDAR technology. We always strive to stay up to date with new technologies and work together to provide our clients with the best possible solutions.";
    textId12a = "Innovative Approach";
    textId12 = "We're always on the lookout for new, creative solutions. We love exploring new technologies and ways to help our clients improve their business and make better decisions.";
    textId13a = "Tailored Solutions";
    textId13 = "Every project is unique, just like our clients. We take the time to understand their specific needs and challenges so we can provide solutions that truly make a difference.";
    textId14a = "Support and Collaboration";
    textId14 = "We’re not just here to get the job done and move on – we’re here to be partners every step of the way. Our door is always open, whether it’s for questions during the project or support afterward.";
    textId16 = "We offer clients advanced solutions in the fields of GIS, photogrammetry, and LiDAR technology, enabling precise analysis and visualization of spatial data."
    textId17 = "Through the development and implementation of innovative web applications, as well as specialized data capture, mapping, and processing services, we optimize efficiency and accuracy for all types of engineering and research projects."
    textId18a = "WebGIS";
    textId18b = "We offer a wide range of services, including the development and implementation of WEB GIS solutions, which enable users to easily access, visualize, and analyze spatial data through interactive web applications. In this way, we allow clients to manage geographic data quickly and efficiently, without the need for specialized software.";
    textId18 = "Photogrammetry";
    textId19 = "We specialize in photogrammetry, enabling precise imaging and mapping of large areas, which is particularly beneficial for topographic and surveying projects. This technology allows for rapid and efficient data collection in the field, optimizing time and cost for our clients.";
    textId20 = "LiDAR";
    textId21 = "Our team is specialized in the processing, classification, and vectorization of LiDAR data. Our expertise in working with LiDAR technology allows us to create accurate 3D models of terrain, objects, and infrastructure, which is essential for projects in engineering, urban planning, and environmental protection.";
    textId22 = "Web sites and applications";
    textId23 = "In addition to our specialized services in GIS, LiDAR, and photogrammetry, we also provide website development, business process automation, and application development services. Our team is proficient in creating modern, functional websites optimized for the best user experience. We also automate business processes, enabling our clients to increase efficiency, reduce manual work, and optimize daily operations. Furthermore, we develop custom applications that meet the specific needs of our clients, whether for business applications, GIS platforms, or tools for data analysis and visualization.";
    textId25 = "Here are some of our projects we done lately. Feel free to check them out."
}