class serbianText {
    translateButton = "ENG";
    textId1 = "Naslovna";
    textId2 = "O nama";
    textId3 = "Usluge";
    textId4 = "Portfolio";
    textId5 = "Kontakt";
    textId6 = "Poruka";
    textId7a = "Hej!";
    textId7 = "Mi smo GisIt. Volimo <br> da razmišljamo prostorno <br> i pravimo sjajne aplikacije."
    textId9 = "GisIt je agencija specijalizovana za pružanje IT usluga iz oblasti Geografskih Informacionih Sistema (GIS), ali i povezanih oblasti kao što su fotogrametrija i LiDAR tehnologija.";
    textId10 = "Naša misija je da unapredimo poslovne procese naših klijenata kroz inovativna tehnološka rešenja koja pomažu u unapređenju njihovih poslovnih procesa i donošenju informisanih i pravovremenih poslovnih odluka.";
    textId11a = "placeholder111";
    textId11 = "Koristimo napredne alate za analizu prostornih podataka i izradu mapa koje olakšavaju planiranje i upravljanje resursima. Fotogrametrija i LiDAR tehnologije koje omogućavaju detaljno prikupljanje prostornih podataka terena ili objekata, našim klijentima pružaju visokokvalitetne 3D modele, što je od ključne važnosti za projekte u oblasti inženjerstva, infrastrukture, zaštite životne sredine i urbanog planiranja.";
    textId12a = "placeholder222";
    textId12 = "Nudimo širok spektar usluga, uključujući razvoj i implementaciju WEB GIS rešenja, koja omogućavaju korisnicima da lako pristupe, vizualizuju i analiziraju prostorne podatke putem interaktivnih web aplikacija. Na ovaj način omogućavamo klijentima da na jednostavan i brz način upravljaju geografskim podacima, bez potrebe za specijalizovanim softverima.";
    textId13a = "placeholder333";
    textId13 = "Posvećeni smo kvalitetu i inovacijama, te se trudimo da naše usluge uvek budu usklađene sa najnovijim trendovima u industriji. Naša agencija pruža profesionalnu podršku svim vrstama klijenata, od malih i srednjih preduzeća do velikih korporacija i javnih institucija, pružajući im rešenja koja omogućavaju bolje donošenje odluka, uštedu vremena i resursa.";
    textId14a = "placeholder444";
    textId14 = "Zadovoljstvo naših klijenata je naš prioritet, a naše usluge su dizajnirane kako bi vam pomogle da postignete željene ciljeve i unapredite efikasnost vaših projekata.";
    textId16 = "Klijentima nudimo napredna rešenja u oblasti GIS-a, fotogrametrije i LiDAR tehnologije, koja omogućavaju preciznu analizu i vizualizaciju prostornih podataka."
    textId17 = "Kroz razvoj i implementaciju inovativnih web aplikacija, kao i specijalizovane usluge snimanja, mapiranja i obrade podataka, optimizujemo efikasnost i tačnost za sve vrste inženjerskih i istraživačkih projekata."
    textId18a = "WebGIS";
    textId18b = "Nudimo širok spektar usluga, uključujući razvoj i implementaciju WEB GIS rešenja, koja omogućavaju korisnicima da lako pristupe, vizualizuju i analiziraju prostorne podatke putem interaktivnih web aplikacija. Na ovaj način omogućavamo klijentima da na jednostavan i brz način upravljaju geografskim podacima, bez potrebe za specijalizovanim softverima.";
    textId18 = "Fotogrametrija";
    textId19 = "Bavimo se fotogrametrijom, omogućavajući precizno snimanje i mapiranje velikih područja, što je posebno korisno za topografske i geodetske projekte. Ova tehnologija omogućava brzo i efikasno prikupljanje podataka sa terena, čime optimizujemo vreme i troškove naših klijenata.";
    textId20 = "LiDAR";
    textId21 = "Naš tim specijalizovan je za obradu, klasifikaciju i vektorizaciju LiDAR podataka. Naša ekspertiza u radu sa LiDAR tehnologijom omogućava nam da kreiramo precizne 3D modele terena, objekata i infrastrukture, što je ključno za projekte u inženjerstvu, urbanom planiranju i zaštiti životne sredine.";
    textId22 = "Izrada web site-ova i aplikacija";
    textId23 = "Pored naših specijalizovanih usluga u oblasti GIS-a, LiDAR-a i fotogrametrije, takođe pružamo i usluge kreiranja web sajtova, automatizacije poslovnih procesa i razvoja aplikacija. Naš tim je stručan u izradi modernih i funkcionalnih web sajtova koji su optimizovani za najbolje korisničko iskustvo. Takođe vršimo automatizuju poslovnih procesa, čime omogućavamo našim klijentima da povećaju efikasnost, smanje manuelni rad i optimizuju svakodnevne operacije. Pored toga, razvijamo prilagođene aplikacije koje zadovoljavaju specifične potrebe naših klijenata, bilo da je u pitanju poslovna aplikacija, GIS platforma ili alat za analizu i vizualizaciju podataka.";
}